CREATE TABLE schools(id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
address TEXT NOT NULL,
landline VARCHAR(255) NOT NULL,
mobile VARCHAR(255) NOT NULL,
enabled TINYINT(1) NOT NULL,
PRIMARY KEY (id))